from enum import Enum


class Codes(str, Enum):
    LIVE_OK = "LIVE_OK"

    STATS_CREATED = "STATS_CREATED"
    STATS_UPDATED = "STATS_UPDATED"
    STATS_FETCHED = "STATS_FETCHED"
    STATS_LIST_FETCHED = "STATS_LIST_FETCHED"

    STATS_NOT_FOUND = "STATS_NOT_FOUND"
    STATS_ALREADY_EXISTS = "STATS_ALREADY_EXISTS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
